In [1]:
Hello Harshal

SyntaxError: invalid syntax (2648255137.py, line 1)

In [2]:
Hello Harshal

SyntaxError: invalid syntax (2648255137.py, line 1)

In [3]:
print("Hello Harshal")

Hello Harshal

In [4]:
import pandas as pdf

ModuleNotFoundError: No module named 'pandas'

In [5]:
import pandas as pf

ModuleNotFoundError: No module named 'pandas'

In [6]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [7]:
import pandas as pdf

ModuleNotFoundError: No module named 'pandas'

In [8]:
pip install pandas openpyxl

Collecting pandas
  Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.1-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\harshal shende\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in c:\users\harshal shende\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.8 MB 7.2 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/9.8 MB 4.9 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/9.8 MB 4.9 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/9.8 MB 4.9 MB/s eta 0:00:02
   --------- ------------------------------ 2.4/9.8 MB 2.5 MB/s eta 0:00:04
   ---------- ----------------------------- 2.6/9.8 MB 2.0 MB/s eta 0:00:04
   ---------- ----------------------------- 2.6/9.8 MB 2.0 MB/s eta 0:00:04
   ----------- ---------------------------- 2.9/9.8 MB 1.6 MB/s eta 0:00:05
   ----------- ---------------------------- 2.9/9.8 MB 1.6 MB/s eta 0:00:05
   ------------ --------------------------- 3.1/9.8 MB 1.5 MB/s eta 0:00:05
   ---------------- ----------------------- 3.9/9.8 MB 1.6 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.8 MB 1.8 MB/s eta 0:00:03
   ----------------------- ---------------- 5.8/9.8 MB 2.0 MB/s eta 0:00:03
   ------------------------- -------------- 6.3/9.8 MB 2.1 MB/s eta 0:00:02
   -------------------------- ------------- 6.6/9.8 MB 2.0 MB/s eta 0:00:02
   ----------------------------- ---------- 7.3/9.8 MB 2.1 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.8 MB 2.2 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.8 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 2.3 MB/s  0:00:04
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading numpy-2.5.1-cp313-cp313-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.4 MB 5.4 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/12.4 MB 3.0 MB/s eta 0:00:04
   ----- ---------------------------------- 1.8/12.4 MB 2.9 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.4 MB 2.8 MB/s eta 0:00:04
   ---------- ----------------------------- 3.4/12.4 MB 3.2 MB/s eta 0:00:03
   --------------- ------------------------ 4.7/12.4 MB 3.6 MB/s eta 0:00:03
   ------------------- -------------------- 6.0/12.4 MB 4.0 MB/s eta 0:00:02
   ------------------------- -------------- 7.9/12.4 MB 4.6 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.4 MB 4.8 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.4 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.4 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 4.8 MB/s  0:00:02
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, et-xmlfile, pandas, openpyxl

   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   ---------------------------------------- 5/5 [openpyxl]

Successfully installed et-xmlfile-2.0.0 numpy-2.5.1 openpyxl-3.1.5 pandas-3.0.5 tzdata-2026.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
import pandas as pd

In [10]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_excel("../Customer_Transactions_Dataset.xlsx")

In [12]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Product_ID,Product_Category,Quantity,Unit_Price,Total_Amount,Payment_Method,Transaction_Status,Acquisition_Channel,Country,City,Device_Type
0,T0001,C049,2025-03-12,P086,Beauty,3,296,888,UPI,Completed,Facebook,India,Hyderabad,Desktop
1,T0002,C103,2025-06-27,P014,Electronics,4,176,704,UPI,Completed,Facebook,India,Mumbai,Tablet
2,T0003,C044,2025-08-09,P005,Home,3,294,882,UPI,Failed,Email,India,Bengaluru,Desktop
3,T0004,C060,2025-01-30,P090,Fashion,1,233,233,UPI,Completed,Organic,India,Mumbai,Tablet
4,T0005,C111,2025-11-02,P001,Fashion,5,254,1270,Wallet,Completed,Organic,India,Hyderabad,Mobile

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction_ID       200 non-null    str
 1   Customer_ID          200 non-null    str
 2   Transaction_Date     200 non-null    str
 3   Product_ID           200 non-null    str
 4   Product_Category     200 non-null    str
 5   Quantity             200 non-null    int64
 6   Unit_Price           200 non-null    int64
 7   Total_Amount         200 non-null    int64
 8   Payment_Method       200 non-null    str
 9   Transaction_Status   200 non-null    str
 10  Acquisition_Channel  200 non-null    str
 11  Country              200 non-null    str
 12  City                 200 non-null    str
 13  Device_Type          200 non-null    str
dtypes: int64(3), str(11)
memory usage: 22.0 KB

In [14]:
df.shape

(200, 14)

In [15]:
df.columns

Index(['Transaction_ID', 'Customer_ID', 'Transaction_Date', 'Product_ID',
       'Product_Category', 'Quantity', 'Unit_Price', 'Total_Amount',
       'Payment_Method', 'Transaction_Status', 'Acquisition_Channel',
       'Country', 'City', 'Device_Type'],
      dtype='str')

In [16]:
df.isnull().sum()

Transaction_ID         0
Customer_ID            0
Transaction_Date       0
Product_ID             0
Product_Category       0
Quantity               0
Unit_Price             0
Total_Amount           0
Payment_Method         0
Transaction_Status     0
Acquisition_Channel    0
Country                0
City                   0
Device_Type            0
dtype: int64

In [17]:
df.isnull().sum()

Transaction_ID         0
Customer_ID            0
Transaction_Date       0
Product_ID             0
Product_Category       0
Quantity               0
Unit_Price             0
Total_Amount           0
Payment_Method         0
Transaction_Status     0
Acquisition_Channel    0
Country                0
City                   0
Device_Type            0
dtype: int64

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction_ID       200 non-null    str
 1   Customer_ID          200 non-null    str
 2   Transaction_Date     200 non-null    str
 3   Product_ID           200 non-null    str
 4   Product_Category     200 non-null    str
 5   Quantity             200 non-null    int64
 6   Unit_Price           200 non-null    int64
 7   Total_Amount         200 non-null    int64
 8   Payment_Method       200 non-null    str
 9   Transaction_Status   200 non-null    str
 10  Acquisition_Channel  200 non-null    str
 11  Country              200 non-null    str
 12  City                 200 non-null    str
 13  Device_Type          200 non-null    str
dtypes: int64(3), str(11)
memory usage: 22.0 KB

In [19]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Product_ID,Product_Category,Quantity,Unit_Price,Total_Amount,Payment_Method,Transaction_Status,Acquisition_Channel,Country,City,Device_Type
0,T0001,C049,2025-03-12,P086,Beauty,3,296,888,UPI,Completed,Facebook,India,Hyderabad,Desktop
1,T0002,C103,2025-06-27,P014,Electronics,4,176,704,UPI,Completed,Facebook,India,Mumbai,Tablet
2,T0003,C044,2025-08-09,P005,Home,3,294,882,UPI,Failed,Email,India,Bengaluru,Desktop
3,T0004,C060,2025-01-30,P090,Fashion,1,233,233,UPI,Completed,Organic,India,Mumbai,Tablet
4,T0005,C111,2025-11-02,P001,Fashion,5,254,1270,Wallet,Completed,Organic,India,Hyderabad,Mobile

In [20]:
git status

SyntaxError: invalid syntax (3528599804.py, line 1)

In [21]:
!git status

On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	../../../.bash_history
	../../../.codeium/
	../../../.copilot/
	../../../.docker/
	../../../.git-for-windows-updater
	../../../.gitconfig
	../../../.idlerc/
	../../../.ipython/
	../../../.lesshst
	../../../.redis-for-vscode/
	../../../.vscode-shared/
	../../../.vscode/
	../../../3D Objects/
	../../../AppData/
	../../../Contacts/
	../../
	../../../Documents/
	../../../Downloads/
	../../../Favorites/
	../../../IntelGraphicsProfiles/
	../../../Links/
	../../../Microsoft/
	../../../Music/
	../../../NTUSER.DAT
	../../../NTUSER.DAT{4d73a84d-d552-11ef-860a-2839268ef0f6}.TM.blf
	../../../NTUSER.DAT{4d73a84d-d552-11ef-860a-2839268ef0f6}.TMContainer00000000000000000001.regtrans-ms
	../../../NTUSER.DAT{4d73a84d-d552-11ef-860a-2839268ef0f6}.TMContainer00000000000000000002.regtrans-ms
	../../../OneDrive/
	../../../Pictures/
	../../../Saved Games/
	../../../Searches/
	../../../Videos/
	../../../demo.txt
	../../../go/
	../../../ntuser.dat.LOG1
	../../../ntuser.dat.LOG2
	../../../ntuser.ini
	../../../python/

nothing added to commit but untracked files present (use "git add" to track)

warning: could not open directory 'AppData/Local/Application Data/': Permission denied
warning: could not open directory 'Application Data/': Permission denied
warning: could not open directory 'Cookies/': Permission denied
warning: could not open directory 'Local Settings/': Permission denied
warning: could not open directory 'My Documents/': Permission denied
warning: could not open directory 'NetHood/': Permission denied
warning: could not open directory 'PrintHood/': Permission denied
warning: could not open directory 'Recent/': Permission denied
warning: could not open directory 'SendTo/': Permission denied
warning: could not open directory 'Start Menu/': Permission denied
warning: could not open directory 'Templates/': Permission denied